/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package robot

import kotlin.test.Test
import kotlin.test.assertEquals

import frc.robot.Vec2

class Vec2Test {
    @Test
    fun add() {
        assertEquals(Vec2(1.0, 1.0) + Vec2(8.0, 9.0), Vec2(9.0, 10.0))
    }

    @Test
    fun dot() {
        assertEquals(Vec2(8.0, 2.0).dot(Vec2(3.0, 2.0)), 28.0)
    }

    // Etc.
}
